name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run Tests
        run: mvn clean test || true

      - name: Show Test Output
        if: always()
        run: |
          echo "Contents of target/"
          ls -la target
          echo "Contents of target/allure-results/"
          ls -la target/allure-results || echo "No allure-results found"

      - name: Generate Allure Report
        if: success() || failure()
        run: |
          if [ -d target/allure-results ]; then
            mvn allure:report
          else
            echo "Skipping report generation: no allure-results."
          fi

      - name: Deploy to GitHub Pages
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/allure-maven-plugin
