name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run Tests
        run: mvn clean test || true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Report to Output Folder
        run: |
          mkdir -p public
          cp -r target/site/allure-maven-plugin/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
